### ISSUE TITLE
ContextStore Upgrade

### ISSUE THREAD

**Issue by amitlimaye** [aporeto-inc/trireme-lib#412]
#### Actual behavior
*Description of the actual behavior.*

#### Expected behavior
*Description of the expected behavior.*

#### Steps to reproduce
*Description of the various steps required to reproduce the error.*

#### Solution proposal
*Description of what you thingk would need to be done.*
The context store today will not be able to handle format changes between restarts or upgrade or trireme. 
If we add fields to the context store and restart we will not be able to recover PU's.
Need to add this capability to the contextstore
#### Installation type
- [ ] console.aporeto.com
- [ ] on-prem
- [ ] dev

> Version: ?
> Customer: ?
> ETA: ?

**Comment by dstiliadis** [comment]
Context store is removed. Closing.
