### ISSUE TITLE
package import

### ISSUE THREAD

**Issue by likhita-8091** [aporeto-inc/trireme-lib#901]
go.aporeto.io/trireme-lib/controller/internal/

- The following packages cannot be imported. Prompt not allowed

**Comment by sibicramesh** [comment]
@CodingJzy Can you share the output of the following commands ?
uname -a
go version

**Comment by likhita-8091** [comment]
Yes, i can。but I seem to know. Everything is internal as a package under the directory. It is not allowed to import, it seems to be the internal mechanism of go. Is this for you to protect private packages? Still unintentionally took the name of this package?

1. uname -a
root@jw-ubuntu01:~/trireme-jw# uname -a
Linux jw-ubuntu01 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

2. go version
root@jw-ubuntu01:~/trireme-jw# go version
go version go1.13.1 linux/amd64
